### ISSUE TITLE
Please acknowledge the license of AsmJit if you take from it

### ISSUE THREAD

**Issue by kobalicek** [playX18/asmkit#1]
Hello,

it's great that you are creating something like AsmJit for rust, I really like the idea. However, I think that when somebody starts taking code line-by-line (including comments) from another project it should be properly attributed as AsmJit has a license too and its API formed after many years of development and feedback. I would not care about few lines, but it seems the whole foundation of asmkit is based on AsmJit pretty much 1:1 (API, classes, even comments, the implementation of foundational concepts, and overall the design of the library).

Here is the AsmJit license:

  - https://github.com/asmjit/asmjit/blob/master/LICENSE.md

I don't mind about using AsmJit as a reference (it's great you have picked it actually and it's open-source for a reason), but I think you should not violate its license.

**Comment by playX18** [comment]
Hello! Sorry for this, I'll modify according files. I was not yet done this because of simply rushing it to make it to work. 
Also thank you for AsmJit! I really like the API, sadly could not port it here nor use asmdb, had to rely on other opcode tables which allow for fully automatic encoding generation from scratch

**Comment by playX18** [comment]
@kobalicek I have updated files which are just RiiRed AsmJit parts and added mention in README, hope it's better now

**Comment by kobalicek** [comment]
Yeah that's much better, thanks! I would recommend you anyway to rewrite the parts to be more like rust anyway :)

Good luck with your project!
